name: CI/CD Pipeline
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
 
      - name: Install dependencies
        run: |
          set +e
          pwd
          ls -la
          python -m pip install --upgrade pip
          pip install -r requirement.txt
 
      -  name: Log in to Docker Hub
         uses: docker/login-action@v2
         with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
 
     # - name: Build Docker image
      # run: docker build -f Application/dockerfile -t flask-app .

      #- name: Push Docker image
       # run: |
        #    docker tag flask-app ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest
         #   docker push ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest

      - name: Build and push Docker image
        run: |
             docker build -t flask-app .
             docker tag flask-app your-dockerhub-username/my-flask-app:latest
             docker push your-dockerhub-username/my-flask-app:latest


          
 